# Дозволити підключення з усіх IP всередині мережі Docker
bind 0.0.0.0

requirepass your_secure_password

# Режим збереження даних (Persistence)
# AOF записує кожну операцію зміни. Це ідеально для "At-Least-Once"
appendonly yes
appendfsync everysec

# Максимальна пам'ять (налаштуйте під себе)
maxmemory 512mb
# Коли пам'ять закінчиться, видаляти старі ключі, які мають термін дії
maxmemory-policy allkeys-lru

loadmodule /opt/redis-stack/lib/rejson.so
loadmodule /opt/redis-stack/lib/redisearch.so

# Логи
loglevel notice