services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: cloth-shop-backend
    restart: always
    environment:
      - DB_HOST=cloth-shop-db
      - DB_PORT=3306
      - ES_HOST=http://elasticsearch:9200
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./es-last-sync.json:/usr/src/app/dist/es-last-sync.json
      - ./redis-last-sync.json:/usr/src/app/dist/redis-last-sync.json

    command: npm run start

    networks:
      - elk-net
    depends_on:
      - elasticsearch

  espocrm:
    image: espocrm/espocrm:latest
    container_name: espocrm
    restart: always
    environment:
      - ESPOCRM_DATABASE_HOST=espocrm-db   # Ім'я контейнера MySQL
      - ESPOCRM_DATABASE_USER=root          # Користувач root для MySQL
      - ESPOCRM_DATABASE_PASSWORD=root      # Пароль root для MySQL
      - ESPOCRM_DATABASE_NAME=espocrm_db    # Ім'я бази даних
      - ESPOCRM_ADMIN_USERNAME=admin       # Ім'я адміністратора EspoCRM
      - ESPOCRM_ADMIN_PASSWORD=admin       # Пароль адміністратора EspoCRM

      # Localization (System Level)
      - TZ=Europe/Kyiv
      - ESPOCRM_LANGUAGE=uk_UA

      # Force config.php parameters via Docker
      - ESPOCRM_CONFIG_PHP_TIMEZONE=Europe/Kyiv
      - ESPOCRM_CONFIG_DEFAULT_TIMEZONE=Europe/Kyiv
      - ESPOCRM_CONFIG_TIME_ZONE=Europe/Kyiv
      - ESPOCRM_CONFIG_WEEK_START=1            # 1 = Monday, 0 = Sunday
      - ESPOCRM_CONFIG_DEFAULT_CURRENCY=UAH
      - ESPOCRM_CONFIG_DATE_FORMAT=DD.MM.YYYY
      - ESPOCRM_CONFIG_TIME_FORMAT=HH:mm

    volumes:
      - espocrm_files:/var/www/html # Том для файлів самої CRM
    ports:
      - "8000:80"
    networks:
      - elk-net

volumes:
  espocrm_files:

networks:
  local-kafka:
    name: local-kafka-shared # Явно вказуємо назву, щоб уникнути префіксів папок
    driver: bridge
  elk-net:
    external: true
    name: elk-network