services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    networks:
      - local-kafka
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093

      # ПРАВИЛЬНІ ЛІСТЕНЕРИ:
      # 9092 - для Windows (localhost)
      # 29092 - для інших контейнерів (наприклад, Kafka-UI)
      # 29093 - для внутрішньої роботи самого контролера Kafka
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG_DIRS: /var/lib/kafka/data # Краще змінити /tmp на volume, щоб дані не зникали

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - local-kafka
    depends_on:
      - broker
    ports:
      - "7777:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      # Тепер порт збігається з внутрішнім PLAINTEXT літенером брокера
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092

volumes:
  kafka_data:
    driver: local

networks:
  local-kafka:
    name: local-kafka-shared # Явно вказуємо назву, щоб уникнути префіксів папок
    driver: bridge
  elk-net:
    external: true
    name: elk-network
