services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"

    networks:
      backend-network:

    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    volumes:
      - zookeeper_data:/data

  clickhouse-01:
    image: clickhouse/clickhouse-server:24.1
    container_name: clickhouse-01
    ports:
      - "8123:8123"
      - "9000:9000"

    networks:
      backend-network:

    volumes:
      - clickhouse_01_data:/var/lib/clickhouse
      - ./config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-02:
    image: clickhouse/clickhouse-server:24.1
    container_name: clickhouse-02
    ports:
      - "8124:8123"
      - "9001:9000"

    networks:
      backend-network:

    volumes:
      - clickhouse_02_data:/var/lib/clickhouse
      - ./config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  backend-network:
    driver: bridge

volumes:
  zookeeper_data:
  clickhouse_01_data:
  clickhouse_02_data: