services:

  gateway:
    build:
      context: ../../gateway
      dockerfile: Dockerfile

    restart: always

    environment:
      PORT: 5000

      # KAFKA
      KAFKA_BROKER: kafka:9092

    expose:
      - "5000"

    networks:
      - backend-network

#    deploy:
#      mode: replicated
#      replicas: 2
#      endpoint_mode: vip
#      resources:
#        limits:
#          cpus: '0.025'
#          memory: 100M

    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M

    develop:
      watch:
        # 1. Слідкуємо за package.json для повної перезбірки (якщо додали новий npm-пакет)
        - path: ../../gateway/
          action: rebuild
          ignore:
            - node_modules/           # шлях вказується ВІДНОСНО папки 'path'

#        # 2. Слідкуємо за ВСІЄЇ папкою backend для швидкої синхронізації коду
#        - path: ../../backend/
#          target: /app                # копіюємо в корінь додатка в контейнері
#          action: rebuild
#          ignore:
#            - node_modules/           # шлях вказується ВІДНОСНО папки 'path'


networks:
  backend-network:
    driver: bridge