services:

  notification-service:
    build:
      context: ../../services/notification-service
      dockerfile: Dockerfile

    restart: always

    environment:
      NODE_ENV: production

      KAFKA_BROKERS: kafka:9092

      REDIS_URL: redis://redis:6379

      TZ: Europe/Kyiv

    expose:
      - "7000"

    depends_on:
      kafka1:
        condition: service_started
      kafka2:
        condition: service_started
      kafka3:
        condition: service_started


      redis:
        condition: service_healthy

    networks:
      - backend-network

    develop:
      watch:
        # 1. Слідкуємо за package.json для повної перезбірки (якщо додали новий npm-пакет)
        - path: ../../services/notification-service/package.json
          action: rebuild

        # 2. Слідкуємо за ВСІЄЇ папкою notification-service для швидкої синхронізації коду
        - path: ../../services/notification-service/
          target: /app                # копіюємо в корінь додатка в контейнері
          action: sync
          ignore:
            - node_modules/           # шлях вказується ВІДНОСНО папки 'path'



networks:
  backend-network:
    driver: bridge