services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: karma-cloth-scheduler
    restart: always
    command: daemon --config /etc/ofelia.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../ofelia/ofelia.conf:/etc/ofelia.conf:ro
    networks:
      - backend-network
    depends_on:
      - shop-api