services:

  products-service:
    build:
      context: ../../services/products-service
      dockerfile: Dockerfile

    restart: always

    environment:
      NODE_ENV: production
      DB_HOST: cloth-shop-db
      DB_PORT: 3306

      REDIS_HOST: redis

    expose:
      - "8004"

    networks:
      - backend-network

    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M

#    deploy:
#      mode: replicated
#      replicas: 2
#      endpoint_mode: vip
#      resources:
#        limits:
#          cpus: '0.025'
#          memory: 100M

    develop:
      watch:
        # 1. Слідкуємо за package.json для повної перезбірки (якщо додали новий npm-пакет)
        - path: ../../services/products-service/
          action: rebuild
          ignore:
            - node_modules/
#
#        # 2. Слідкуємо за ВСІЄЇ папкою analytics-service для швидкої синхронізації коду
#        - path: ../../services/analytics-service/
#          target: /app                # копіюємо в корінь додатка в контейнері
#          action: rebuild
#          ignore:
#            - node_modules/           # шлях вказується ВІДНОСНО папки 'path'


networks:
  backend-network:
    driver: bridge