services:

  shop-api:
    build:
      context: ../../services/shop-api
      dockerfile: Dockerfile

    restart: always

    environment:
      NODE_ENV: production

      DATABASE_URL: mysql://root:root@cloth-shop-db:3306/shop

      REDIS_URL: redis://redis:6379

      KAFKA_BROKERS: kafka:29092

      ELASTICSEARCH_URL: http://elasticsearch:9200

      TZ: Europe/Kyiv

    expose:
      - "9000"

    depends_on:
      cloth-shop-db:
        condition: service_healthy

      redis:
        condition: service_healthy

      elasticsearch:
        condition: service_healthy

      kafka1:
        condition: service_started
      kafka2:
        condition: service_started
      kafka3:
        condition: service_started

    networks:
      - backend-network

    develop:
      watch:
        # 1. Слідкуємо за package.json для повної перезбірки (якщо додали новий npm-пакет)
        - path: ../../services/shop-api/package.json
          action: rebuild

        # 2. Слідкуємо за ВСІЄЇ папкою shop-api для швидкої синхронізації коду
        - path: ../../services/shop-api/
          target: /app                # копіюємо в корінь додатка в контейнері
          action: sync
          ignore:
            - node_modules/           # шлях вказується ВІДНОСНО папки 'path'



networks:
  backend-network:
    driver: bridge