services:
  espocrm-db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_DATABASE: espocrm_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3308:3306"

    volumes:
      - espocrm_db_data:/var/lib/mysql

    networks:
      - backend-network

    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

volumes:
  espocrm_db_data:
    name: espocrm-db-data


networks:
  backend-network:
    driver: bridge
