services:

  redis:
    image: redis:7-alpine

    restart: always

    ports:
      - "6379:6379"

    command: ["redis-server", "--requirepass", "root"]

    volumes:
      - redis_data:/data

    networks:
      - backend-network

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  redis-insight:
    image: redis/redis-stack:latest

    restart: always

    ports:
      - "8001:8001"

    networks:
      - backend-network


volumes:
  redis_data:
    name: redis-data


networks:
  backend-network:
    driver: bridge