services:

  redis:
    image: redis:7-alpine

    restart: always

    ports:
      - "6379:6379"

    command: ["redis-server", "--requirepass","your_secure_password"]

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

    networks:
      - backend-network


  redis-insight:
    image: redis/redis-stack:latest

    restart: always

    ports:
      - "8001:8001"

    networks:
      - backend-network


volumes:
  redis_data:
    name: redis-data


networks:
  backend-network:
    driver: bridge